#!/usr/bin/env python
import sys

from passwordhash import generate_password_digest

if __name__ == '__main__':
  if len(sys.argv) not in [3,4]:
    print('Usage: hashauthenticator secret_key user [len]')
    sys.exit(1)

  secret_key = sys.argv[1]
  username = sys.argv[2]
  length = int(sys.argv[3]) if len(sys.argv) > 3 else 6

  password = generate_password_digest(username, secret_key, length)

  password = password[:length]
  print(password)
